version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    versioning-strategy: auto

    groups:
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "react-*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"

      build-tools:
        patterns:
          - "next"
          - "tailwindcss"
          - "postcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"

      testing-tools:
        patterns:
          - "jest"
          - "jest-*"
          - "babel-jest"
          - "identity-obj-proxy"
        update-types:
          - "minor"
          - "patch"
