version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-test-renderer"
    ignore:
    open-pull-requests-limit: 10
