version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    match:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-test-renderer"
    update-strategy: "batch"
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    match:
      - dependency-name: "*"
        exclude:
          - dependency-name: "react"
          - dependency-name: "react-dom"
          - dependency-name: "react-test-renderer"
    update-strategy: "auto"
