version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    groups:
      # React and related libraries
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@testing-library/*"
      
      # Next.js and build tools
      build-tools:
        patterns:
          - "next"
          - "tailwindcss"
          - "postcss"
          - "@tailwindcss/*"
      
      # Testing tools
      testing-tools:
        patterns:
          - "jest*"
          - "babel-jest"
          - "identity-obj-proxy"
    
    # Common settings for all groups
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
